# Generated by Django 2.2.1 on 2019-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
